### ISSUE TITLE
Tracking issue for 0.2.0

### ISSUE THREAD

**Issue by PieterPenninckx** [PieterPenninckx/rsynth#104]
Version 0.2.0 can make some breaking changes, so this is a list of things I would like to change before version 0.2.0:

- [ ] Remove deprecated things
- [ ] Add support for lv2 (#43)
- [ ] Add support for alsa
- [ ] Remove default implementation for `AudioWriter::number_of_channels`
- [ ] Offline backend: support multiple midi inputs and outputs.
- [ ] Offline backend: use `ContextualEventHandler` instead of `EventHandler`
- [x] Offline backend: support stopping
- [ ] Remove support for VST 2.4
- [x] ~VST: use indexed events (more uniform)~
- [ ] Use a different mechanism for audio buffers
- [ ] ~Make the API around `AudioChunk` more clean.~
- [ ] Decide on the data type for sampling frequencies.
- [x] Change the `CommonMidiPortMeta` trait so that no memory allocation is (i.e. do not require to return a `String`).
- [ ] Make it possible to dynamically choose the name of the ~plugin~ application (e.g. if there are multiple instances). I.e.: the method `name` from `CommonPluginMeta` should not just return a slice.

**Comment by PieterPenninckx** [comment]
I'm closing this issue since `rsynth` has been deprecated. See the README.md for more information.
